#!/bin/bash

echo -e "Sisesta kasutaja vanuse \c" #Kysib vanust ja loeb seda vanust
read vanus

if test $vanus -gt 0 -a $vanus -lt 11 #Kontrollib vanust ja v2ljastab
then
        echo "Sa oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18 #Kontrollib vanust ja v2ljastab
then    
        echo "Sa oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63 #Kontrollib vanust ja v2ljastab
then
        echo "Sa oled t2iskasvanu"
elif test $vanus -ge 63 #Kontrollib vanust ja v2ljastab
then
        echo "Sa oled seenior" 
else
        echo "Vigane sisend" V2ljastab veateate
fi
