#!/bin/bash

echo -e "Sisesta kuu number \c"
read kuu

if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 #V2ljastab antud kuu j2rgi aastaaja
then
        echo "Praegu on talv"
elif test $kuu -ge 3 -a $kuu -le 5 #V2ljastab antud kuu j2rgi aastaaja
then
        echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8 #V2ljastab antud kuu j2rgi aastaaja
then
        echo "Praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11 #V2ljastab antud kuu j2rgi aastaaja
then
        echo "Praegu on sygis"
else
        echo "Antud kuu numbrit ei ole olemas"
fi
