#!/bin/bash

echo -n "Sisesta kellaaeg täistunnina: " #Kysib kellaaja
read kell

if test $kell -ge 6 -a $kell -lt 12 #Kontrollib kas on hommik ja tervitab
then
	echo "Tere hommikust"

elif test $kell -ge 12 -a $kell -lt 18 #Kontrollib kas on p2evane aeg ja tervitab
then
	echo "Tere päevast"

elif test $kell -ge 18 -a $kell -lt 22 #Kontrollib kas on õhtu ja tervitab
then
	echo "Tere õhtust"

elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6 #Kontrollib kas on 66 ja tervitab
then
	echo "Head ööd"

else
	echo "Arv ei ole 0 ja 24 vahel" #Kui on sisestatud vale aeg
fi