#!/bin/bash
# Arvu numbrite summa leidmine

echo -n "Sisesta suvaline t2isarv: "
read arv
echo -n "Arvu $arv numbrite summa on "

if [ $arv -lt 0 ]; then # kontrollib, kas arv on positiivne
        arv=$(($arv * -1))
	echo -n "-"
fi

# arvutame summat

summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "$summa" 

